// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBLuJxcdPkRB1730iTh-ClP_H1qzxrIcA',
    appId: '1:28983122953:web:5fc27abecc05081cafecd8',
    messagingSenderId: '28983122953',
    projectId: 'pseb-matq',
    authDomain: 'pseb-matq.firebaseapp.com',
    databaseURL: 'https://pseb-matq-default-rtdb.firebaseio.com',
    storageBucket: 'pseb-matq.appspot.com',
    measurementId: 'G-KYZ2VF905K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACta_Jfbds1Yvb4jD4SbbBvwmV1XpDc18',
    appId: '1:28983122953:android:25f058435d079213afecd8',
    messagingSenderId: '28983122953',
    projectId: 'pseb-matq',
    databaseURL: 'https://pseb-matq-default-rtdb.firebaseio.com',
    storageBucket: 'pseb-matq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjkaui2WdrNr_FOnblYK56dvW5FP_3byQ',
    appId: '1:28983122953:ios:da9cf214d3282efbafecd8',
    messagingSenderId: '28983122953',
    projectId: 'pseb-matq',
    databaseURL: 'https://pseb-matq-default-rtdb.firebaseio.com',
    storageBucket: 'pseb-matq.appspot.com',
    iosBundleId: 'com.example.satyaNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjkaui2WdrNr_FOnblYK56dvW5FP_3byQ',
    appId: '1:28983122953:ios:48b8cc1ba9d55370afecd8',
    messagingSenderId: '28983122953',
    projectId: 'pseb-matq',
    databaseURL: 'https://pseb-matq-default-rtdb.firebaseio.com',
    storageBucket: 'pseb-matq.appspot.com',
    iosBundleId: 'com.example.satyaNew.RunnerTests',
  );
}
